/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/highlight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Detect brand names in page text
         * @description Accepts chunks of page text and matches them against 14k known brands
         *     from the Wikidata database. Returns brand names found in the text.
         *     No LLM call — pure in-memory string matching.
         */
        post: operations["highlightBrands"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/company-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get brand details and Canadian heritage
         * @description Looks up a company in the local Wikidata database. If the company is
         *     Canadian (by country, founding location, or TSX listing), enriches the
         *     response with LLM-generated history and Canadian significance.
         */
        post: operations["getCompanyInfo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: string;
        };
        HealthResponse: {
            ok: boolean;
            /** @enum {string} */
            agent: "openrouter" | "fallback";
        };
        TextChunk: {
            /** @description Unique identifier for the chunk */
            id: string;
            /** @description Text content from the page (max 6000 chars used) */
            text: string;
        };
        HighlightRequest: {
            /** @description Optional search goal (currently unused, reserved for future) */
            goal?: string;
            /** @description Text chunks from the web page */
            chunks: components["schemas"]["TextChunk"][];
            /**
             * @description Word to return if no brands are found
             * @default Google
             */
            fallbackWord: string;
        };
        HighlightResponse: {
            /** @description Brand names found in the text */
            phrases: string[];
            /**
             * @description Where the results came from
             * @enum {string}
             */
            source: "database" | "fallback";
        };
        HighlightErrorResponse: {
            error: string;
            phrases: string[];
            /** @enum {string} */
            source: "error";
        };
        CompanyInfoRequest: {
            /** @description Company or brand name to look up */
            company: string;
        };
        CanadianSignals: {
            country_is_canada: boolean;
            founded_in_canada: boolean;
            listed_on_tsx: boolean;
        };
        CompanyInfo: {
            name: string;
            /** @description Inception date or "Unknown" */
            founded: string;
            /** @description Comma-separated founder names or "Unknown" */
            founders: string;
            /** @description City, Country */
            headquarters: string;
            country: string;
            /** @description Comma-separated industries */
            industry: string;
            website?: string | null;
            stockExchanges?: string[];
            canadianSignals?: components["schemas"]["CanadianSignals"];
            isCanadian: boolean;
            /** @description 2-3 sentence company description */
            description?: string;
            /** @description 4-6 sentence history (Canadian focus if applicable) */
            history?: string;
            /** @description Why this company matters to Canada (Canadian brands only) */
            canadianSignificance?: string;
            products?: string[];
            funFact?: string;
        };
        CompanyInfoResponse: {
            /** @description The queried company name */
            company: string;
            /** @description Company details, or null if not found */
            info?: components["schemas"]["CompanyInfo"] | null;
            isCanadian: boolean;
            /**
             * @description - database: non-Canadian brand, DB info only
             *     - database+llm: Canadian brand, enriched with LLM history
             *     - not-found: brand not in database
             *     - fallback: no API key configured
             * @enum {string}
             */
            source: "database" | "database+llm" | "not-found" | "fallback";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    highlightBrands: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HighlightRequest"];
            };
        };
        responses: {
            /** @description Brand names found in the text */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HighlightResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HighlightErrorResponse"];
                };
            };
        };
    };
    getCompanyInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyInfoRequest"];
            };
        };
        responses: {
            /** @description Company information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyInfoResponse"];
                };
            };
            /** @description Missing company name */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
